#!/usr/bin/sh
xrdb -merge "$HOME/.Xresources"
xsetroot -cursor_name left_ptr

# apps
killall -q sxhkd
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &
killall -q polybar
polybar -c $HOME/.config/polybar/config.ini mainbar &
pkill flameshot 2>/dev/null
flameshot &
copyq --start-server &

# monitors
bspc monitor Virtual1 -d 1 2 3 4 5 6 7 8 9 
feh --bg-fill /home/wrs/bag/wallpapers/tux_whitebg.png &
# xsetroot -solid "#FFFFFF"

# nodes config
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config focused_border_color "#ff0000"
bspc config border_width 2
bspc config window_gap 0
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc rule -a Pcmanfm state=floating
bspc rule -a pcmanfm state=floating
bspc rule -a Mousepad state=floating
bspc rule -a mousepad state=floating
bspc rule -a copyq state=floating
bspc rule -a Dolphin state=floating
bspc rule -a dolphin state=floating
